server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: note
          uri: lb://note
          predicates:
            - Path=/note/**
          filters:
            - StripPrefix=1
