server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: films
          uri: lb://films
          predicates:
            - Path=/films/**
          filters:
            - StripPrefix=1
        - id: tickets
          uri: lb://tickets
          predicates:
            - Path=/tickets/**
          filters:
            - StripPrefix=1
